#include "libpe.h"
using namespace libpe;

const std::map<DWORD, std::wstring> g_mapLibpeErrors = {
	{ CALL_LOADPE_FIRST, L"CALL_LOADPE_FIRST" },
{ FILE_OPEN_FAILED, L"FILE_OPEN_FAILED" },
{ FILE_SIZE_TOO_SMALL, L"FILE_SIZE_TOO_SMALL" },
{ FILE_CREATE_FILE_MAPPING_FAILED, L"FILE_CREATE_FILE_MAPPING_FAILED" },
{ FILE_MAP_VIEW_OF_FILE_FAILED, L"FILE_MAP_VIEW_OF_FILE_FAILED" },
{ FILE_SECTION_DATA_CORRUPTED, L"FILE_SECTION_DATA_CORRUPTED" },
{ IMAGE_TYPE_UNSUPPORTED, L"IMAGE_TYPE_UNSUPPORTED" },
{ IMAGE_DOS_SIGNATURE_MISMATCH, L"IMAGE_DOS_SIGNATURE_MISMATCH" },
{ IMAGE_HAS_NO_DOS_HEADER, L"IMAGE_HAS_NO_DOS_HEADER" },
{ IMAGE_HAS_NO_RICH_HEADER, L"IMAGE_HAS_NO_RICH_HEADER" },
{ IMAGE_NT_SIGNATURE_MISMATCH, L"IMAGE_NT_SIGNATURE_MISMATCH" },
{ IMAGE_HAS_NO_NT_HEADER, L"IMAGE_HAS_NO_NT_HEADER" },
{ IMAGE_HAS_NO_FILE_HEADER, L"IMAGE_HAS_NO_FILE_HEADER" },
{ IMAGE_HAS_NO_OPTIONAL_HEADER, L"IMAGE_HAS_NO_OPTIONAL_HEADER" },
{ IMAGE_HAS_NO_DATA_DIRECTORIES, L"IMAGE_HAS_NO_DATA_DIRECTORIES" },
{ IMAGE_HAS_NO_SECTIONS, L"IMAGE_HAS_NO_SECTIONS" },
{ IMAGE_HAS_NO_EXPORT_DIR, L"IMAGE_HAS_NO_EXPORT_DIR" },
{ IMAGE_HAS_NO_IMPORT_DIR, L"IMAGE_HAS_NO_IMPORT_DIR" },
{ IMAGE_HAS_NO_RESOURCE_DIR, L"IMAGE_HAS_NO_RESOURCE_DIR" },
{ IMAGE_HAS_NO_EXCEPTION_DIR, L"IMAGE_HAS_NO_EXCEPTION_DIR" },
{ IMAGE_HAS_NO_SECURITY_DIR, L"IMAGE_HAS_NO_SECURITY_DIR" },
{ IMAGE_HAS_NO_BASERELOC_DIR, L"IMAGE_HAS_NO_BASERELOC_DIR" },
{ IMAGE_HAS_NO_DEBUG_DIR, L"IMAGE_HAS_NO_DEBUG_DIR" },
{ IMAGE_HAS_NO_ARCHITECTURE_DIR, L"IMAGE_HAS_NO_ARCHITECTURE_DIR" },
{ IMAGE_HAS_NO_GLOBALPTR_DIR, L"IMAGE_HAS_NO_GLOBALPTR_DIR" },
{ IMAGE_HAS_NO_TLS_DIR, L"IMAGE_HAS_NO_TLS_DIR" },
{ IMAGE_HAS_NO_LOADCONFIG_DIR, L"IMAGE_HAS_NO_LOADCONFIG_DIR" },
{ IMAGE_HAS_NO_BOUNDIMPORT_DIR, L"IMAGE_HAS_NO_BOUNDIMPORT_DIR" },
{ IMAGE_HAS_NO_IAT_DIR, L"IMAGE_HAS_NO_IAT_DIR" },
{ IMAGE_HAS_NO_DELAY_IMPORT_DIR, L"IMAGE_HAS_NO_DELAY_IMPORT_DIR" },
{ IMAGE_HAS_NO_COMDESCRIPTOR_DIR, L"IMAGE_HAS_NO_COMDESCRIPTOR_DIR" }
};

const std::map<WORD, std::wstring> g_mapResType {
	{ 1, L"CURSOR" },
{ 2, L"BITMAP" },
{ 3, L"ICON" },
{ 4, L"MENU" },
{ 5, L"DIALOG" },
{ 6, L"STRING" },
{ 7, L"FONTDIR" },
{ 8, L"FONT" },
{ 9, L"ACCELERATOR" },
{ 10, L"RCDATA" },
{ 11, L"MESSAGETABLE" },
{ 12, L"GROUP_CURSOR" },
{ 14, L"GROUP_ICON" },
{ 16, L"VERSION" },
{ 17, L"DLGINCLUDE" },
{ 19, L"PLUGPLAY" },
{ 20, L"VXD" },
{ 21, L"ANICURSOR" },
{ 22, L"ANIICON" },
{ 23, L"HTML" },
{ 24, L"MANIFEST" }
};

//These are identificators of all the controls: list, hex, tree.
constexpr auto IDC_LIST_DOSHEADER = 0x0001;
constexpr auto IDC_LIST_RICHHEADER = 0x0002;
constexpr auto IDC_LIST_NTHEADER = 0x0003;
constexpr auto IDC_LIST_FILEHEADER = 0x0004;
constexpr auto IDC_LIST_OPTIONALHEADER = 0x0005;
constexpr auto IDC_LIST_DATADIRECTORIES = 0x0006;
constexpr auto IDC_LIST_SECHEADERS = 0x0007;
constexpr auto IDC_LIST_EXPORT = 0x0008;
constexpr auto IDC_LIST_EXPORT_FUNCS = 0x0009;
constexpr auto IDC_LIST_IMPORT = 0x000A;
constexpr auto IDC_LIST_IMPORT_ENTRY = 0x000B;
constexpr auto IDC_LIST_EXCEPTION = 0x000C;
constexpr auto IDC_LIST_SECURITY = 0x000D;
constexpr auto IDC_LIST_SECURITY_ENTRY = 0x000E;
constexpr auto IDC_LIST_RELOCATIONS = 0x000F;
constexpr auto IDC_LIST_RELOCATIONS_ENTRY = 0x0010;
constexpr auto IDC_LIST_DEBUG = 0x0011;
constexpr auto IDC_LIST_DEBUG_ENTRY = 0x0012;
constexpr auto IDC_LIST_ARCHITECTURE = 0x0013;
constexpr auto IDC_LIST_GLOBALPTR = 0x0014;
constexpr auto IDC_LIST_TLS = 0x0015;
constexpr auto IDC_LIST_TLS_CALLBACKS = 0x0016;
constexpr auto IDC_LIST_LOADCONFIG = 0x0017;
constexpr auto IDC_LIST_BOUNDIMPORT = 0x0018;
constexpr auto IDC_LIST_IAT = 0x0019;
constexpr auto IDC_LIST_DELAYIMPORT = 0x001A;
constexpr auto IDC_LIST_DELAYIMPORT_FUNCS = 0x001B;
constexpr auto IDC_LIST_COMDESCRIPTOR = 0x001C;

constexpr auto IDC_TREE_LEFT_MAIN = 0x0100;
constexpr auto IDC_TREE_RESOURCE = 0x0101;
constexpr auto IDC_TREE_RESOURCE_TOP = 0x0102;
constexpr auto IDC_TREE_RESOURCE_BOTTOM = 0x0103;

constexpr auto IDC_HEX_RIGHT_BOTTOM_LEFT = 0x0200;
constexpr auto IDC_HEX_RIGHT_TOP_RIGHT = 0x0201;

constexpr auto IDC_SHOW_FILE_SUMMARY = 0x0300;